"""
Python script to get the metrics DataFrame generated by the PatchIF model training and
print it in a better shape
"""

import os
import pandas as pd

from moviad.utilities.manage_files import generate_path,get_most_recent_dir, get_most_recent_file

df_path = generate_path(
    basepath = os.getcwd(),
    folders = [
        "patchif_results",
        "metrics",
        "mvtec",
        "pill",
        "PatchIF_EIF+",
        "mobilenet_v2",
    ]
)

df_exp_path = get_most_recent_dir(df_path,file_pos=0)
df_dirpath = get_most_recent_dir(df_exp_path, file_pos=0)
df_filepath = get_most_recent_file(df_dirpath, file_pos=0)

print('#'* 50)
print(f"Metrics DataFrame file found at: {df_filepath}")
print('#'* 50)

df = pd.read_csv(df_filepath)

print('#'* 50)
print("Metrics DataFrame:")
print(df.T.to_markdown())
print('#'* 50)


